### PR TITLE
Corrected docs for .progress

### PR DESCRIPTION
**Pull request by jeffijoe**
According to the docs, .progress is a property, while in reality it's actually a function. :)

### CODE REVIEW

**Comment by freeall** [comment]
Thanks :) Not a fan of the `getter` word so I removed that. But otherwise looks good.

**Comment by jeffijoe** [comment]
Fair enough. :)

P.S. Cool to see another JS dev from Denmark :D

**Comment by freeall** [comment]
Likewise. There's quite a lot of us :)

**Comment by jeffijoe** [comment]
I thought Denmark was mostly all about Java or C#, hehe

**Comment by freeall** [comment]
Not sure about Aalborg but in Copenhagen there's quite a lot of js developers. Both frontend and backend.

**Comment by jeffijoe** [comment]
I'm from Aabenraa which is in southern Denmark, here there's like 2 of us or something.

**Comment by freeall** [comment]
So is https://github.com/mafintosh :)

**Comment by jeffijoe** [comment]
He's from Aabenraa? Profile says Copenhagen. :P

**Comment by freeall** [comment]
From Aabenraa, lives in Copenhagen

**Comment by jeffijoe** [comment]
That's pretty cool :D

**Pull request merged**
