### PR TITLE
chore(package): update dependencies

### LINKED ISSUE #15: Upgrade dependencies ?
Would it be possible to upgrade dependencies ?
through2 now exists in major version 2, and speedometer in major version 1.

Maybe devDependencies could be updated too.

Thanks you.

### PR DESCRIPTION
**Pull request by ungoldman**
Noticed discussion on #18 has stalled, and I'm getting an unspecified warning for `object-keys@0.4.0` when installing another package that depends on `progress-stream`. Thought I would just bump the deps in an isolated PR to move this forward and close #15.

### CODE REVIEW

**Comment by freeall** [comment]
Thanks @ungoldman. Released as `1.2.1`.

**Comment by ungoldman** [comment]
Thanks @freeall! Looks like it didn't make it to the registry though 😢

https://www.npmjs.com/package/progress-stream === 1.2.0

**Comment by freeall** [comment]
Try now :)

**Comment by triccardi-systran** [comment]
Changing `throught2` dependency from v0.2 to v2.0 is a major change: they migrated from Streams2 to Streams3, this may impact `progress-stream` users. Is this reasonable to push that with only a version bump on patch ?
This could be seen as a new feature: it provides Streams3 behavior, which should globally be backward compatible.
This could also be seen as a breaking change: in some cases Streams3 breaks Streams2 compatibility.

**Comment by freeall** [comment]
@triccardi-systran very good point! I've unpublished `1.2.1` and published as `2.0.0` instead.

**Comment by thomas-riccardi** [comment]
Thanks for your quick action!

The "Streams2 vs Streams3" could also be documented on the master README, and a 1.x branch could be created too, with a similar warning on its README.

**Pull request merged**
